### ISSUE TITLE
Release with `fluentd-plugin-gcs` v0.4.2

### ISSUE THREAD

**Issue by kapec94** [fluent/fluentd-kubernetes-daemonset#1426]
There is a PR #1420 that is recently merged. It updates the `fluentd-plugin-gcs` dependency. This updated dependency is still not present in images available in the Docker Hub.

Is there a timeline when will a new version of the image be released?

**Comment by ashie** [comment]
Sorry for delaying the release.

I'm planning to release a new version of fluentd-kubernetes-daemonset with fluentd v1.16.0 in this week.

Because we found a bug in v1.16.0, we skipped releasing fluentd-kubernetes-daemonset for it.
I've release fluentd v1.16.1 just now: https://github.com/fluent/fluentd/pull/4149

**Comment by ashie** [comment]
We released v1.16.1 images last week.
