### ISSUE TITLE
Fluentd logging on kubernetes skips logs on log rotation

### ISSUE THREAD

**Issue by tom932** [fluent/fluentd-kubernetes-daemonset#156]
Currently, I have the following architecuture in kubernetes:

  - In a pod, a service and a sidecar container (called `logger`) is running.
  - The services writes to a file, the sidecar container reads that file and writes it to stdout.
  - The fluentd daemonset is configured to read the output (which is collected in a file in `/var/log/containers/*_logger-*.log`, which is a link to another file (the latest file since the last file rotation, to the older files, no link points).
  - Always 3 log messages belong together (some same fields)
  - This configuration works as expected for thousands of messages.

However, here is the problem:

I noticed that fluentd sometimes only forwards logmessage 1 or 2 of the 3 messages that belong together, although all 3 messages are written by the service and the sidecar container.

For the explaination, assume 1 is forwarded, 2 and 3 not. After some research, I found out, that in such cases, message 1 is the last message before the log rotates, message 2 and 3 are in another file (where the symbolic link points to since the rotation, and therefore should be read).

Therefore, it looks like fluentd skips some lines before continue reading at the new file after the kubernetes log rotation.

Is this a known problem?
Why are fluentd and kubernetes behaving like this?
What can I do to prevent this behavior? It is required that fluentd forwards all the log messages!
I am using the docker-image `fluent/fluentd-kubernetes-daemonset:v0.12.33-elasticsearch`

If more information is required, please let me know.

Question also posted on https://stackoverflow.com/questions/51097947/fluentd-logging-on-kubernetes-skips-logs-on-log-rotation for the case it is no issue with fluentd, but a configuration problem.

**Comment by rubencabrera** [comment]
Hi, we are also experiencing this. For us, a significant memory usage started to happen at the same moment the logs disappeared, so we ended up following [this issue](https://github.com/fluent/fluentd/issues/1941#issuecomment-415136580)

The fix for that is in release 1.2.5. We use fluentd-kubernetes-daemonset:v1.2-debian-elasticsearch, which hasn't been updated yet to use 1.2.5, but I'm posting this so you know and we can track the results.

**Comment by snedi** [comment]
I have the similar issue. I have 2 log sources in fluentd and I am sending the output to Elasticsearch. If I leave only one one log source in the configuration everything works. If I try to have 2 sources being sent to Elasticsearch then one of the source is missing in the Elasticsearch.

**Comment by congliu01** [comment]
According to [Fluentd in_tail plugin comment](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_tail.rb#L254-L258), in_tail plugin log rotation check doesn't support file path with "*" very well, and it could cause log duplication. It's interesting that this issue is actually log skip instead of duplication. I was wondering if that comment is still valid.
