### ISSUE TITLE
[error]: config error file="/fluentd/etc/fluent.conf" error="Invalid Kubernetes API v1 endpoint https://172.28.0.1:443/api: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"

### ISSUE THREAD

**Issue by Jacky2** [fluent/fluentd-kubernetes-daemonset#200]
Why did I create fluentd startup times wrong?

[error]: config error file="/fluentd/etc/fluent.conf" error="Invalid Kubernetes API v1 endpoint https://172.28.0.1:443/api: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"

**Comment by Jacky2** [comment]
I have solved it.


add env into your yaml

        env:
          - name: KUBERNETES_SERVICE_HOST
            value: "192.168.251.187"
          - name: KUBERNETES_SERVICE_PORT
            value: "6443"

**Comment by TanTan-TT** [comment]
> I have solved it.
> 
> add env into your yaml
> 
> ```
>     env:
>       - name: KUBERNETES_SERVICE_HOST
>         value: "192.168.251.187"
>       - name: KUBERNETES_SERVICE_PORT
>         value: "6443"
> ```

Hi, I have this problem too, but it does not work by using your solution. Do you have any other config? Or could you share your yaml?

**Comment by heidemn** [comment]
@TanTan-TT  we had a similar problem with the example `fluentd-daemonset-elasticsearch-rbac.yaml` from this repo.
Maybe it helps in your case.

The example DaemonSet YAML worked out of the box, but after transforming it to Terraform code, it no longer worked.
The problem was that the token for the fluentd ServiceAccount was not mounted into the Pods.

Using the Terraform Kubernetes provider, `kubernetes_service_account.automount_service_account_token` was `false` by default.
Using kubectl, the same property was `true` by default.

Setting the property to `true` solved the problem.

**Comment by zanoubia** [comment]
> kubernetes_service_account.automount_service_account_token

Same problem, translating fluentd-daemonset-elasticsearch-rbac.yaml into terraform, but your fix didn't work for me :(

**Comment by zanoubia** [comment]
Worked after all :)
I add automount_service_account_token = true in kubernetes_daemonset.spec.spec

**Comment by heidemn** [comment]
@zanoubia Thanks - suddenly, this additional one was also required for us.
Probably a Terraform provider version change.

For the record, I think you meant `kubernetes_daemonset.spec.template.spec` ("template" was missing).
