### ISSUE TITLE
Fluentd misses log file when >1 app log rotation happens back to back

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluentd-kubernetes-daemonset#465]
**Summary**
When an application container generates a burst of logs, such that > 1 log rotation happens back to back within a few seconds, then the Fluentd daemonset doesn't seem to detect all the log rotations (i.e. only detects SOME of the log rotations) and, thus, completely misses the intermediate/middle log files.

Eg. If the app has generated a big enough burst of logs to trigger 2 log rotations back to back within a few seconds, that means there are now 3 app container log files:
1. app.log.2 (oldest)
|
|
1st log rotation 
|
v
2. app.log.1
|
|
2nd log rotation
|
v
3. app.log (newest)

In this scenario, Fluentd thinks only 1 log rotation has happened, and only captures logs written to the first/oldest and third/newest log files -- the entire middle file is missed!

**Details**
I am running the Fluentd daemonset on a Kubernetes cluster. As is recommended for any Kubernetes cluster, to collect the container logs, Fluentd is configured to tail /var/log/containers.

As is standard with Kubernetes clusters, /var/log/containers consists of symlinks pointing to the actual Docker container log files in /var/lib/docker/containers.
i.e. The file structure looks like this:
```
/var/log/containers                     /var/lib/docker/containers
-------------------                     --------------------------
    app-symlink.log -----------------------------> app.log
```

My cluster is configured to rotate the container log files (in /var/lib/docker/containers) when any of them reaches 100 MB. 
For my testing, I used a sample app container that can generate a burst of logs on demand -- for my cluster, having the app generate 500,000 logs was enough to trigger 2 log rotations back to back, creating a total of 3 container log files in /var/lib/docker/containers.
i.e. The file structure looked like this:
```
Before any log rotation:

/var/log/containers                     /var/lib/docker/containers
-------------------                     --------------------------
    app-symlink.log -----------------------------> app.log


#############


After 1st log rotation:

/var/log/containers                     /var/lib/docker/containers
-------------------                     --------------------------
    app-symlink.log -----------------------------> app.log (newer)
                                                   app.log.1 (older, full)


#############


After 2nd log rotation:

/var/log/containers                     /var/lib/docker/containers
-------------------                     --------------------------
    app-symlink.log -----------------------------> app.log (newest)
                                                   app.log.1 (older, full)
                                                   app.log.2 (oldest, full)
```

To show how quickly these log rotations are happening, here are some example timestamps from my testing:
(Note that timestamps in Unix are not the creation time of the file -- instead, they are the last modified time)
```
2020-07-16 18:26:17.602009787 app.log
2020-07-16 18:26:11.865931348 app.log.1
2020-07-16 18:26:04.553831355 app.log.2
```

**So, at this point, 2 log rotations have happened, creating 3 log files -- however, if we look at Fluentd's internal logs, we see that it has detected only 1 log rotation!** 
Specifically, based on the timestamps, it appears to have missed the 1st log rotation and only detected the 2nd one.
```
2020-07-16 18:11:32.744 following tail of /var/log/containers/app-symlink.log
...
2020-07-16 18:26:16.707 detected rotation of /var/log/containers/app-symlink.log; waiting 5 seconds
2020-07-16 18:26:16.707 following tail of /var/log/containers/app-symlink.log
```

**Since Fluentd has only detected 1 log rotation, it wrongly thinks that only 2 log files have been created -- specifically, it only captures logs from the 1st (oldest) and 3rd (newest) log files, completely missing the 2nd log file (_app.log.1_)!**

**Attempted Fixes**

_1. rotate_wait:_

Initially, it seemed obvious what was wrong, and how to fix it: As far as I understand, by default, when Fluentd's tail plugin detects a log rotation, it does not immediately start tailing the new log file -- instead, it keeps tailing the old log file for 5 seconds to catch any last logs being flushed to that old log file, before moving to the new log file.

My theory was that, in my example with 3 log files, when Fluentd detects the first log rotation (from 1st to 2nd log file), it keeps tailing that 1st log file for 5 seconds -- unbeknownst to it, in that 5 second period when Fluentd is temporarily 'blind', another log rotation has happened (from 2nd to 3rd log file), which Fluentd does not know about. Thus, after 5 seconds, Fluentd THINKS it is moving to the 2nd log file, but it is actually moving to the 3rd log file, and has completely missed the real 2nd log file.

The 5s delay is controlled by the [rotate_wait](https://docs.fluentd.org/input/tail#rotate_wait) tail plugin param. Given my theory, I assumed that the 'fix' would be as simple as reducing _rotate_wait_ -- thus, Fluentd would be blind for a shorter amount of time, and would move on to the real 2nd log file before the 2nd log rotation happens.
**Unfortunately, when I tried reducing _rotate_wait_ to 1s (and even 0s), it had no effect -- Fluentd still only detected 1 log rotation, and still only tailed the 1st and 3rd log files.
Also, if we examine the timestamps of Fluentd's internal logs, it seems more likely that, contrary to my theory above, Fluentd is actually missing the 1st log rotation, and only detecting the 2nd/final one.**

_2. refresh_interval:_

I then tried reducing the [refresh_interval](https://docs.fluentd.org/input/tail#refresh_interval) tail plugin param from its default value of 60s. **Unfortunately, reducing _refresh_interval_ to 1s (and even 0s) had no effect either.**

_3. rotate_wait and refresh_interval:_
**Finally, I tried various combinations of _rotate_wait_ and _refresh_interval_, but none of them had any effect.**
Eg.
```
rotate_wait: 5s    refresh_interval: 1s
rotate_wait: 1s    refresh_interval: 1s
rotate_wait: 0s    refresh_interval: 1s
rotate_wait: 0s    refresh_interval: 0s
```

**Mitigation**
At this point, I am out of ideas on how to fix this in Fluentd. 

When I searched online, I could find only one other person with the same issue as me: [link](https://medium.com/ninjavan-tech/logging-with-efk-in-gke-e11676f781e6)
In that article, they don't have a Fluentd fix either -- instead, they seem to have increased the log file size that triggers log rotation to make it harder to trigger 2 log rotations in a row, as a workaround on the cluster side.

**For now, I am planning to do the cluster workaround as a short-term mitigation, but I would much prefer an actual fix that I can apply on the Fluentd side. Please let me know if you have any ideas, or need more information from me!**

**Config Details**

Kubernetes cluster log rotation settings: Container log file rotates when it reaches `100 MB`, total of `3 log files` retained.

Fluentd Docker image version: `v1.10.4-debian-forward-1.0`

Fluentd tail config:
```
<source>
  @type tail

  tag kubernetes.*

  path /var/log/containers/*.log
  exclude_path [
    "/var/log/containers/fluentd-agent-*.log",
    ...
    ]
  
  pos_file /var/log/container.log.pos

  <parse>
    @type "#{ENV['FLUENT_CONTAINER_TAIL_PARSER_TYPE'] || 'json'}"
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </parse>

  path_key log_file
  read_from_head true
  pos_file_compaction_interval 24h
  
  # Default settings
  rotate_wait 5s
  refresh_interval 60s

  # The inotify-based file watcher (i.e. stat_watcher) does not seem to work -- thus, we disable stat_watcher and enable watch_timer instead.
  enable_watch_timer true
  enable_stat_watcher false
</source>
```

**Comment by takryo00** [comment]
@pranavmarla 
https://github.com/fluent/fluentd-kubernetes-daemonset/issues/366#issuecomment-720019764

**Comment by pranavmarla** [comment]
@takryo00 Thanks for linking to #366! I'm afraid I must have missed it at the time.

However, if I understand [this comment](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/366#issuecomment-720019764) from #366, the suggestion is that, because Fluentd on Kubernetes is tailing the symlinks rather than the actual log files themselves, Fluentd cannot detect any rotations in the log files.

However, to clarify, that is not the behaviour I see here: In my testing, Fluentd DOES usually detect the log rotation properly, even though it's tailing the symlinks. The issue here only arises when there are MULTIPLE log rotations happening one after the other very quickly -- in that case, Fluentd only catches SOME of the log rotations (whereas we expect it to catch ALL of the log rotations).

**Comment by pranavmarla** [comment]
Bump

**Comment by cosmo0920** [comment]
Fluentd's tailing file plugin which is `in_tail` is keeping reference for rotated file in 5 seconds by default:
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_tail.rb#L71

There are not changing for this parameter in this daemonset.
Do you know or measure how frequent to be log rotated your container files?

**Comment by pranavmarla** [comment]
Hi @cosmo0920:

1. I don't know how frequently my container log files get rotated. To be clear though, what I described here is not an issue I run into on a daily basis. This is an edge case -- _if_ my app container generates a burst of logs that is big enough to trigger 2 log rotations back to back, then Fluentd misses one of those log rotations.
2. As mentioned in my original post, I already experimented with reducing the `rotate_wait` param to 1s (and even 0s), but it made no difference. Similarly with the `refresh_interval` param.
3. Also, as mentioned in my original post, if the issue was with the 5s `rotate_wait` param, I would expect Fluentd to miss the _second_ log rotation (since it happens during those 5 seconds when it's still tailing the first, rotated log file). But, if we look at the timestamps of Fluentd's internal logs, it looks like Fluentd is actually missing the _first_ log rotation.

**Comment by pranavmarla** [comment]
bump

**Comment by ashie** [comment]
How about using `read_bytes_limit_per_second`?
Since you are using `enable_watch_timer`, rotation will be checked every seconds in usual.
But the rotation handler might be blocked by other reading tasks for huge files (it might take a few seconds to a few minutes).

refs
* https://github.com/fluent/fluentd/issues/3423#issuecomment-866521054
* https://github.com/fluent/fluentd/issues/3434

**Comment by sebv7** [comment]
Hi @Harmelodic 
Have you gained any insight if this is happening with Fluent Bit?

**Comment by Harmelodic** [comment]
Yeah, investigated Fluent Bit, and whilst I can't remember exactly what the issue was but it wasn't a serviceable alternative - I _think_ it was because it had the same issue.

Also contacted Google, since the cluster is running on Google Cloud, about their GCP Monitoring as an alternative, and they use Fluent Bit and see similar issues, which is why they have a limit of 120,000 number of entries,write API calls per minute.

Ended up just sticking with FluentD and reducing the logging on the applications running on the cluster, to reduce bursting of logs and thus reduce the impact of this issue.

**Comment by kayrus** [comment]
I also experience this issue. I wonder why `kubectl logs -f my-pod` handles the log rotation, but fluentd doesn't.

**Comment by jbilliau-rcd** [comment]
We are having the same issue. During log rotations, on certain nodes (completely random it seems), fluentd is just skipping entire log files. We've tweaked every setting we can think of, and can't fix the problem of missing logs.

**Comment by damomurf** [comment]
We're regularly seeing Fluentd "lose" file tailing on even just single rotations and then pick them up on the next rotation - what results is something of a square wave of log processing metrics. The only thing we've found that mitigates the issue is to enable `open_on_every_update true` with minimal observed i/o impact. Without studying the code, I do wonder how much of that defeats the purpose of inotify at all though.

**Comment by lololozhkin** [comment]
We are facing the same issue :( At this moment we'll try to increase size of logfiles, but there are now guarantees, that in spikes of load logs size will be smaller..

**Comment by mherda64** [comment]
We also had issues with logs missing under high load and eventually it was related to high log rotation frequency. Kubelet's default log rotation parmeters in [CRI containers](https://github.com/kubernetes/kubernetes/pull/59898) seemed to be too small for fluentd to keep up when rotation happened often. Increasing the log rotation size threshold (from 50MB up to 500MB) helped.

**Comment by zillaer** [comment]
Vector seems resolved this issue
https://github.com/vectordotdev/vector-test-harness/blob/f6702941c917dc1703962a1fc44bf3a99b012ccf/cases/file_rotate_truncate_correctness/README.md

**Comment by kayrus** [comment]
do you have any progress on this issue?

**Comment by darekg11** [comment]
We are facing similar issues when fluentd needs to process logs coming in big burst. Around of couple MB/s

We are using EKS on AWS with `containerd` runtime.
I can reproduce that case every time and I would like to share my discoveries - what worked / what now and hoping for some feedback from fluentd core team to shed some light on it and maybe help resolving this.

We are running `fluentd-kubernetes-daemonset:v1.16.1-debian-graylog-1.2-multi`
```
2023-10-20 12:11:42 +0000 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
2023-10-20 12:11:42 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2023-10-20 12:11:42 +0000 [info]: gem 'fluentd' version '1.16.1'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-concat' version '2.5.0'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.15'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-gelf-hs' version '1.0.8'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-grok-parser' version '2.6.2'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-json-in-json-2' version '1.0.2'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '3.2.0'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-parser-cri' version '0.1.1'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.3'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.1'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
2023-10-20 12:11:42 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.5'
```

Our `tail` config is as follow:
```
<source>
  @type tail
  @id in_tail_container_logs
  path /var/log/containers/*.log
  refresh_interval 2

  exclude_path [
    "/var/log/containers/alb-ingress-controller-*",
    "/var/log/containers/cluster-autoscaler-*",
    "/var/log/containers/logger-fluentd-*",
    "/var/log/containers/logentries-*",
    "/var/log/containers/retool-*",
    "/var/log/containers/fluentd*",
    "/var/log/containers/graylog-*",
    "/var/log/containers/global-monitoring-grafana-*",
    "/var/log/containers/global-monitoring-prometheus-*",
    "/var/log/containers/monitoring-grafana-*",
    "/var/log/containers/monitoring-prometheus-*",
    "/var/log/containers/monitoring-postgres-*",
    "/var/log/containers/etcd*",
    "/var/log/containers/aws-node-*",
    "/var/log/containers/kube-addon-manager*",
    "/var/log/containers/kube-controller-manager*",
    "/var/log/containers/kube-apiserver*",
    "/var/log/containers/kube-proxy-*",
    "/var/log/containers/coredns-*",
    "/var/log/containers/shopify-app-*"
  ]
  pos_file /var/log/fluentd-containers.log.pos
  tag kubernetes.*
  @label @kubernetes
  read_from_head true
  encoding 'UTF-8'
  <parse>
    @type cri
  </parse>
</source>
```

I tried pretty much everything:
- different value for `rotate_wait`
- disabling `state_watcher` and enabling only `watch_timer` and vice-versa
- different value for `read_bytes_limit_per_second`
- `follow_inodes` disabled / enabled

Since we are using `containerd` runtime then the kubelet is responsible for log rotation: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/logs/container_log_manager.go

The default settings are to keep 5 files, each file with max size of 10Mi. GZipping the oldest files
When log rotation happens kubelet is always keeping last rotated file uncomopressed to allow fluentd scrap it.

We are seeing issues with missing log when files are becoming compressed, ie in situation when there are 3 files rotated totally.
On K8S Node it looks like this:
`0.log` file which is current file to which logs are send, this log is placed in `var/log/pods/X-pod/Y-container`. Those files are symlinked in `/var/log/containers` and that path is used in `tail`
`0.log.20231018-081423.gz` - compressed rotated file
`0.log.20231018-081443` - last rotated file which is not getting compressed for sake of software such as fluentd

Now the issue is only happening when compression happens.
Can it be a case when fluent-d is still scrapping the file and then because it gets deleted it just stops? Deletion is happening here: https://github.com/kubernetes/kubernetes/blob/3825e206cb162a7ad7431a5bdf6a065ae8422cf7/pkg/kubelet/logs/container_log_manager.go#L407

If so, how fluent-d handles renaming of last rotated file and symlinks here? When log exceeds given size threshold then it is rotated aka renamed here: https://github.com/kubernetes/kubernetes/blob/3825e206cb162a7ad7431a5bdf6a065ae8422cf7/pkg/kubelet/logs/container_log_manager.go#L418
?

The only time we don't see any issues and all logs are scrapped and pushed to Graylog is when we increase max file size threshold before rotating to 100Mi then only 2 logs files are produced:
`0.log`
`0.log.20231018-081443`

In this case since there is no need to make another  rotation and therefore forcing `0.log.20231018-081443` to be compressed and removed - in such scenario everything works fine.

My questions:
1. Did anybody observed similar behavior? How did you overcome it?
2. How can I log how many handles to files and to which files are opened by fluent-d. I would really like to see if there is a possibility that fluent-d is processing both `0.log` and `0.log.20231018-081443` at the same time
