### ISSUE TITLE
Newest release cloudwatch containers no longer start

### ISSUE THREAD

**Issue by ianjoneill** [fluent/fluentd-kubernetes-daemonset#50]
Following the merge of #44 yesterday and the subsequent image updates on docker hub, the cloudwatch docker containers fail to start up.

There is an existing issue for the aws sdk for ruby that details the problem: https://github.com/aws/aws-sdk-ruby/issues/1590. Basically the latest sdk (3.x) is now modularised, so needs to be imported in a different way.

Unfortunately 3.0.0 of the aws sdk was released over a month after that merge request was created - so if it had been merged when the request had been opened, the new images would work correctly.

This re-release of existing tags on docker hub has completely broken our previously stable build. When a release is made, existing tags that reference a specific version (e.g. `v0.12.33-cloudwatch`) shouldn't be updated, but should be released using a brand new tag. For generic tags (such as `cloudwatch`) updating existing tags is OK, because people expect them to be updated.

**Comment by pvdvreede** [comment]
We also had this problem - it would be a lot better if, rather than updating docker tags they were versioned - if there had been new tags for this rather than us just repulling the same tag, then we would not have had this invisible issue crop out of nowhere when we had not touched our logging containers.

So aside from fixing that actual cause of the bug, can there be a change the building of the images to have immutable tags - or tags down to a specific build of this image so that we can pin our containers and know they will never change?
