### ISSUE TITLE
CVEs reported in fluentd image 

### ISSUE THREAD

**Issue by rramadoss4** [fluent/fluentd-kubernetes-daemonset#573]
Fluentd image version: fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-azureblob-1.1

Package:
gnutls28

Vulnerabilities:
CVE-2021-20231
CVE-2021-20232
CVE-2020-24659

================
Package:
rexml

Vulnerabilities:
CVE-2021-28965
CVE-2020-36327

================
Package:
nettle

Vulnerabilities:
CVE-2021-20305
CVE-2021-3580

================
Package:
libxml2

Vulnerablities:
CVE-2021-3516
CVE-2021-3517
CVE-2021-3537
CVE-2021-3518
CVE-2020-24977

 There seems to be  many vulnerabilities in this image. Could you please fix these vulnerabilities and compliance issues in the image?

**Comment by ashie** [comment]
Thanks for the report.
But I confirmed that there is no actual vulnerabilities you pointed out in this image.

> gnutls28
> CVE-2021-20231
> CVE-2021-20232
> CVE-2020-24659

https://security-tracker.debian.org/tracker/CVE-2021-20231
https://security-tracker.debian.org/tracker/CVE-2021-20232
https://security-tracker.debian.org/tracker/CVE-2020-24659

They are fixed in gnutls28-3.6.7-4+deb10u7.
And fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-azureblob-1.1 already uses it:

```
root@365275f98f95:~# dpkg -l | grep gnutls
ii  libgnutls30:amd64       3.6.7-4+deb10u7            amd64        GNU TLS library - main runtime library
```

> rexml
> [CVE-2021-28965](https://github.com/advisories/GHSA-8cr8-4vfw-mr7h)
> [CVE-2020-36327](https://github.com/advisories/GHSA-fp4w-jxhp-m23p)

It's bundled library in Ruby 2.6.7, yes it's includes the vulnerable library.
But the fluentd and its plugins in this image doesn't use rexml.

> nettle
> CVE-2021-20305
> CVE-2021-3580

https://security-tracker.debian.org/tracker/CVE-2021-20305
https://security-tracker.debian.org/tracker/CVE-2021-3580

They are fixed in nettle-3.4.1-1+deb10u1.
And fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-azureblob-1.1 already uses it:

```
root@365275f98f95:~# dpkg -l | grep nettle
ii  libnettle6:amd64        3.4.1-1+deb10u1            amd64        low level cryptographic library (symmetric and one-way cryptos)
```

> libxml2
> CVE-2021-3516
> CVE-2021-3517
> CVE-2021-3537
> CVE-2021-3518
> CVE-2020-24977

https://security-tracker.debian.org/tracker/CVE-2021-3516
https://security-tracker.debian.org/tracker/CVE-2021-3517
https://security-tracker.debian.org/tracker/CVE-2021-3537
https://security-tracker.debian.org/tracker/CVE-2021-3518

It fixed in libxml2-2.9.4+dfsg1-7+deb10u2.
And fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-azureblob-1.1 already uses it:

```
# dpkg -l | grep libxml2
ii  libxml2:amd64           2.9.4+dfsg1-7+deb10u2      amd64        GNOME XML library
ii  libxml2-dev:amd64       2.9.4+dfsg1-7+deb10u2      amd64        Development files for the GNOME XML library
```
